# -*- coding: utf-8 -*-
"""CI/CD 流水线自动生成：GitHub Actions / GitLab CI。"""

from __future__ import annotations

from pathlib import Path
from typing import Any


def _write(path: Path, content: str, encoding: str = "utf-8") -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding=encoding)
    return path


GITHUB_ACTIONS_CI = '''\
# CI Pipeline — generated by MAWP
name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  # ── 后端 ──
  backend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/api
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff mypy pytest pytest-asyncio httpx

      - name: Lint (ruff)
        run: ruff check . --output-format=github
        continue-on-error: true

      - name: Type check (mypy)
        run: mypy . --ignore-missing-imports || true
        continue-on-error: true

      - name: Syntax check
        run: |
          python -m py_compile main.py
          for f in $(find . -name "*.py" -not -path "./__pycache__/*"); do
            python -m py_compile "$f"
          done

      - name: Smoke test
        run: |
          python -c "from main import app; print('app loaded:', app)"
          python -c "
          from fastapi.testclient import TestClient
          from main import app
          client = TestClient(app)
          r = client.get('/health')
          assert r.status_code == 200, f'health check failed: {r.status_code}'
          print('health check passed')
          "

  # ── 前端 ──
  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: apps/web/package-lock.json

      - name: Install dependencies
        run: |
          if [ -f pnpm-lock.yaml ]; then pnpm install --frozen-lockfile;
          elif [ -f yarn.lock ]; then yarn install --frozen-lockfile;
          else npm ci || npm install; fi

      - name: Build
        run: |
          if [ -f package.json ] && grep -q '"build"' package.json; then
            npm run build
          else
            echo "No build script, skipping"
          fi

  # ── Docker 构建 ──
  docker-build:
    runs-on: ubuntu-latest
    needs: [backend-test, frontend-build]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deploy/Dockerfile.backend
          push: false
          tags: ${{ github.repository }}-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deploy/Dockerfile.frontend
          push: false
          tags: ${{ github.repository }}-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ── 部署（可选，需要配置 secrets）──
  deploy:
    runs-on: ubuntu-latest
    needs: docker-build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Deploy notification
        run: |
          echo "TODO: Configure deployment"
          echo "Options:"
          echo "  - docker-compose -p ${{ github.event.repository.name }} up -d --build"
          echo "  - Deploy to cloud (Vercel/Netlify/Railway/Fly.io)"
          echo "  - kubectl apply -f k8s/"
'''

GITHUB_ACTIONS_CD = '''\
# CD Pipeline — generated by MAWP
name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deploy/Dockerfile.backend
          push: true
          tags: ghcr.io/${{ github.repository }}-backend:latest,ghcr.io/${{ github.repository }}-backend:${{ github.sha }}

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deploy/Dockerfile.frontend
          push: true
          tags: ghcr.io/${{ github.repository }}-frontend:latest,ghcr.io/${{ github.repository }}-frontend:${{ github.sha }}

      - name: Deploy via SSH (optional)
        if: ${{ vars.DEPLOY_HOST != '' }}
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd ${{ vars.DEPLOY_PATH }}
            docker-compose -p ${{ github.event.repository.name }} pull
            docker-compose -p ${{ github.event.repository.name }} up -d --build
            docker image prune -f
'''

GITLAB_CI = '''\
# GitLab CI — generated by MAWP
stages:
  - test
  - build
  - deploy

variables:
  PYTHON_VERSION: "3.11"
  NODE_VERSION: "20"

# ── 后端测试 ──
backend-test:
  stage: test
  image: python:${PYTHON_VERSION}-slim
  before_script:
    - cd apps/api
    - pip install -r requirements.txt
    - pip install ruff mypy pytest pytest-asyncio httpx
  script:
    - ruff check . || true
    - mypy . --ignore-missing-imports || true
    - python -m py_compile main.py
    - python -c "from main import app; print('app loaded:', app)"
    - python -c "
        from fastapi.testclient import TestClient
        from main import app
        client = TestClient(app)
        r = client.get('/health')
        assert r.status_code == 200
        print('health check passed')
      "

# ── 前端构建 ──
frontend-build:
  stage: test
  image: node:${NODE_VERSION}-alpine
  before_script:
    - cd apps/web
    - |
      if [ -f pnpm-lock.yaml ]; then
        npm install -g pnpm && pnpm install --frozen-lockfile
      elif [ -f yarn.lock ]; then
        yarn install --frozen-lockfile
      else
        npm ci || npm install
      fi
  script:
    - |
      if grep -q '"build"' package.json; then
        npm run build
      else
        echo "No build script, skipping"
      fi

# ── Docker 构建 ──
docker-build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - docker info
  script:
    - docker build -f deploy/Dockerfile.backend -t $CI_REGISTRY_IMAGE/backend:latest .
    - docker build -f deploy/Dockerfile.frontend -t $CI_REGISTRY_IMAGE/frontend:latest .
    - |
      if [ -n "$CI_REGISTRY_PASSWORD" ]; then
        docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
        docker push "$CI_REGISTRY_IMAGE/backend:latest"
        docker push "$CI_REGISTRY_IMAGE/frontend:latest"
      fi
  only:
    - main
    - develop

# ── 部署 ──
deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
  script:
    - echo "TODO: Configure deployment via SSH"
    - |
      if [ -n "$DEPLOY_HOST" ]; then
        ssh -o StrictHostKeyChecking=no "$DEPLOY_USER@$DEPLOY_HOST" "
          cd $DEPLOY_PATH
          docker-compose -p $CI_PROJECT_NAME pull
          docker-compose -p $CI_PROJECT_NAME up -d --build
          docker image prune -f
        "
      fi
  only:
    - main
  when: manual
'''


def scaffold_cicd(
    project_path: Path | str,
    *,
    platform: str = "github",
) -> dict[str, Any]:
    """为项目生成 CI/CD 流水线文件。
    
    Args:
        project_path: 项目根路径
        platform: "github" 或 "gitlab"
    
    Returns:
        生成的文件列表
    """
    project_path = Path(project_path).resolve()
    result: dict[str, Any] = {
        "ok": True,
        "project_path": str(project_path),
        "platform": platform,
        "files": [],
    }

    if platform.lower() in ("github", "gh", "actions"):
        gh_dir = _ensure_dir(project_path / ".github" / "workflows")
        ci_path = gh_dir / "ci.yml"
        _write(ci_path, GITHUB_ACTIONS_CI)
        result["files"].append({"path": ".github/workflows/ci.yml", "type": "ci"})

        cd_path = gh_dir / "cd.yml"
        _write(cd_path, GITHUB_ACTIONS_CD)
        result["files"].append({"path": ".github/workflows/cd.yml", "type": "cd"})

    elif platform.lower() in ("gitlab", "gl"):
        gl_path = project_path / ".gitlab-ci.yml"
        _write(gl_path, GITLAB_CI)
        result["files"].append({"path": ".gitlab-ci.yml", "type": "ci_cd"})

    else:
        # 两个都生成
        gh_dir = _ensure_dir(project_path / ".github" / "workflows")
        _write(gh_dir / "ci.yml", GITHUB_ACTIONS_CI)
        _write(gh_dir / "cd.yml", GITHUB_ACTIONS_CD)
        gl_path = project_path / ".gitlab-ci.yml"
        _write(gl_path, GITLAB_CI)
        result["files"].extend([
            {"path": ".github/workflows/ci.yml", "type": "ci"},
            {"path": ".github/workflows/cd.yml", "type": "cd"},
            {"path": ".gitlab-ci.yml", "type": "ci_cd"},
        ])

    result["count"] = len(result["files"])
    return result


def _ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path
