# -*- coding: utf-8 -*-
"""大项目 Deliver 辅助：任务规范化、冒烟脚本、默认 metric_command。"""

from __future__ import annotations

from pathlib import Path
from typing import Any

SMOKE_SCRIPT = '''\
"""Phase smoke check — generated by MAWP project_mode."""
from __future__ import annotations

import importlib.util
import os
import py_compile
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
API = ROOT / "apps" / "api"
WEB = ROOT / "apps" / "web"
errors: list[str] = []
warnings: list[str] = []

if not API.is_dir():
    errors.append("missing apps/api")
else:
    py_files = list(API.rglob("*.py"))
    if not py_files:
        errors.append("apps/api has no .py files")
    for p in py_files:
        try:
            py_compile.compile(str(p), doraise=True)
        except Exception as exc:  # noqa: BLE001
            errors.append(f"syntax {p.relative_to(ROOT)}: {exc}")
    req = API / "requirements.txt"
    pyproject = API / "pyproject.toml"
    if not req.is_file() and not pyproject.is_file():
        errors.append("apps/api missing requirements.txt or pyproject.toml")
    mains = list(API.glob("main.py")) + list(API.glob("**/main.py"))
    if mains:
        text = mains[0].read_text(encoding="utf-8", errors="ignore")
        if "FastAPI" not in text and "flask" not in text.lower() and "app" not in text:
            errors.append("apps/api main entry looks empty (no app framework markers)")

    # 装配门禁：含 APIRouter 的 routers/*.py 与根目录 module_*.py 必须 include_router
    main_py = API / "main.py"
    if main_py.is_file():
        main_txt = main_py.read_text(encoding="utf-8", errors="ignore")
        candidates = []
        routers_dir = API / "routers"
        if routers_dir.is_dir():
            candidates.extend(routers_dir.rglob("*.py"))
        for rp in API.glob("*.py"):
            if rp.name.startswith("_") or rp.name == "main.py":
                continue
            if rp.stem.startswith(("seed", "model", "test")):
                continue
            candidates.append(rp)
        seen: set = set()
        for rp in sorted(candidates, key=lambda p: p.as_posix()):
            key = str(rp)
            if key in seen:
                continue
            seen.add(key)
            if rp.name.startswith("_"):
                continue
            body = rp.read_text(encoding="utf-8", errors="ignore")
            if "APIRouter(" not in body:
                continue
            rel = rp.relative_to(API).as_posix()
            mod = rel[:-3].replace("/", ".")
            stem = rp.stem
            mounted = bool(
                re.search(rf"include_router\\s*\\([^)]*\\b{re.escape(stem)}\\b", main_txt)
                or re.search(rf"from\\s+{re.escape(mod)}\\s+import\\b", main_txt)
                or re.search(
                    rf"from\\s+routers\\s+import\\s+[^\\n]*\\b{re.escape(stem)}\\b",
                    main_txt,
                )
            )
            if not mounted:
                errors.append(
                    f"unmounted router: {rel} (missing include_router in apps/api/main.py)"
                )

    # L0 默认：只做语法/装配检查。L1/L2 需显式 MAWP_SMOKE_LIVE=1 / INSTALL=1
    do_api_install = os.environ.get("MAWP_SMOKE_API_INSTALL", "0").strip() not in {
        "0",
        "false",
        "False",
    }
    if do_api_install and req.is_file():
        import shutil
        import subprocess

        if shutil.which("python"):
            try:
                proc_i = subprocess.run(
                    ["python", "-m", "pip", "install", "-r", str(req)],
                    cwd=str(API),
                    capture_output=True,
                    text=True,
                    timeout=int(os.environ.get("MAWP_SMOKE_API_INSTALL_TIMEOUT", "300")),
                    check=False,
                )
                if proc_i.returncode != 0:
                    tail = ((proc_i.stdout or "")[-500:] + "\\n" + (proc_i.stderr or "")[-500:])
                    errors.append(f"api install failed (exit={proc_i.returncode}): {tail.strip()[:500]}")
                else:
                    print("SMOKE API INSTALL: ok")
            except subprocess.TimeoutExpired:
                errors.append("api install timed out")
            except Exception as exc:  # noqa: BLE001
                warnings.append(f"api install skipped/failed: {exc}")
        else:
            warnings.append("api install skipped: python not found")

if not WEB.is_dir():
    errors.append("missing apps/web")
else:
    has_entry = (
        (WEB / "index.html").is_file()
        or any(WEB.rglob("*.tsx"))
        or any(WEB.rglob("*.jsx"))
        or any(WEB.rglob("*.html"))
        or any(WEB.rglob("*.vue"))
    )
    if not has_entry:
        errors.append("apps/web has no index.html / *.tsx|jsx|html|vue")

    index_html = WEB / "index.html"
    if index_html.is_file():
        idx_txt = index_html.read_text(encoding="utf-8", errors="ignore")
        for hp in sorted(WEB.glob("*.html")):
            if hp.name.lower() == "index.html":
                continue
            if hp.name not in idx_txt and ("./" + hp.name) not in idx_txt:
                errors.append(
                    f"unlinked page: {hp.name} (missing from index.html)"
                )

    pkg = WEB / "package.json"
    if not pkg.is_file():
        warnings.append("apps/web missing package.json (skip web build smoke)")
    else:
        meta: dict = {}
        try:
            import json

            meta = json.loads(pkg.read_text(encoding="utf-8"))
            scripts = meta.get("scripts") or {}
            if "build" not in scripts:
                errors.append("apps/web package.json has no build script")
            # 结构级冒烟：常见工程入口
            has_cfg = any(
                (WEB / name).is_file()
                for name in (
                    "vite.config.ts",
                    "vite.config.js",
                    "vite.config.mjs",
                    "next.config.js",
                    "next.config.mjs",
                    "next.config.ts",
                    "webpack.config.js",
                )
            )
            if not has_cfg and not (WEB / "index.html").is_file():
                warnings.append("apps/web: no vite/next/webpack config detected")
        except Exception as exc:  # noqa: BLE001
            errors.append(f"apps/web package.json unreadable: {exc}")
            meta = {}

        # Build 级冒烟：可选 auto-install，再 npm/pnpm/yarn build
        do_build = os.environ.get("MAWP_SMOKE_WEB_BUILD", "0").strip() not in {
            "0",
            "false",
            "False",
        }
        do_install = os.environ.get("MAWP_SMOKE_WEB_INSTALL", "0").strip() not in {
            "0",
            "false",
            "False",
        }
        node_modules = WEB / "node_modules"
        if do_build and "build" in (meta.get("scripts") or {}):
            import shutil
            import subprocess

            if (WEB / "pnpm-lock.yaml").is_file() and shutil.which("pnpm"):
                pm = "pnpm"
                install_cmd = ["pnpm", "install", "--frozen-lockfile"]
                build_cmd = ["pnpm", "run", "build"]
            elif (WEB / "yarn.lock").is_file() and shutil.which("yarn"):
                pm = "yarn"
                install_cmd = ["yarn", "install", "--frozen-lockfile"]
                build_cmd = ["yarn", "build"]
            elif shutil.which("npm"):
                pm = "npm"
                install_cmd = ["npm", "ci"] if (WEB / "package-lock.json").is_file() else ["npm", "install"]
                build_cmd = ["npm", "run", "build"]
            else:
                pm = ""
                install_cmd = []
                build_cmd = []
                warnings.append("web build skipped: npm/pnpm/yarn not found")

            if build_cmd and not node_modules.is_dir():
                if do_install and install_cmd:
                    try:
                        # frozen 失败时回退普通 install
                        proc_i = subprocess.run(
                            install_cmd,
                            cwd=str(WEB),
                            capture_output=True,
                            text=True,
                            timeout=int(os.environ.get("MAWP_SMOKE_WEB_INSTALL_TIMEOUT", "300")),
                            check=False,
                        )
                        if proc_i.returncode != 0 and pm in {"pnpm", "yarn", "npm"}:
                            fallback = (
                                ["pnpm", "install"]
                                if pm == "pnpm"
                                else ["yarn", "install"]
                                if pm == "yarn"
                                else ["npm", "install"]
                            )
                            proc_i = subprocess.run(
                                fallback,
                                cwd=str(WEB),
                                capture_output=True,
                                text=True,
                                timeout=int(os.environ.get("MAWP_SMOKE_WEB_INSTALL_TIMEOUT", "300")),
                                check=False,
                            )
                        if proc_i.returncode != 0:
                            tail = ((proc_i.stdout or "")[-500:] + "\\n" + (proc_i.stderr or "")[-500:])
                            errors.append(
                                f"web install failed (exit={proc_i.returncode}): {tail.strip()[:500]}"
                            )
                        else:
                            print("SMOKE WEB INSTALL: ok via", pm)
                    except subprocess.TimeoutExpired:
                        errors.append("web install timed out")
                    except Exception as exc:  # noqa: BLE001
                        warnings.append(f"web install skipped/failed: {exc}")
                else:
                    warnings.append(
                        "web build skipped: apps/web/node_modules missing "
                        "(set MAWP_SMOKE_WEB_INSTALL=1 to auto-install)"
                    )

            if build_cmd and (WEB / "node_modules").is_dir() and not errors:
                try:
                    proc = subprocess.run(
                        build_cmd,
                        cwd=str(WEB),
                        capture_output=True,
                        text=True,
                        timeout=int(os.environ.get("MAWP_SMOKE_WEB_BUILD_TIMEOUT", "180")),
                        check=False,
                    )
                    if proc.returncode != 0:
                        tail = ((proc.stdout or "")[-800:] + "\\n" + (proc.stderr or "")[-800:])
                        errors.append(
                            f"web build failed (exit={proc.returncode}): {tail.strip()[:600]}"
                        )
                    else:
                        print("SMOKE WEB BUILD: ok via", " ".join(build_cmd))
                except subprocess.TimeoutExpired:
                    errors.append("web build timed out")
                except Exception as exc:  # noqa: BLE001
                    warnings.append(f"web build skipped/failed: {exc}")
        elif not do_build:
            warnings.append("web build skipped (MAWP_SMOKE_WEB_BUILD=0)")

# Live / HTTP 验收：L0 默认关闭；设 MAWP_SMOKE_LIVE=1 才打 /health 与 ACCEPTANCE 用例
live = os.environ.get("MAWP_SMOKE_LIVE", "0").strip() not in {"0", "false", "False"}
if live and not errors and (API / "main.py").is_file():
    try:
        sys.path.insert(0, str(API))
        spec = importlib.util.spec_from_file_location("mawp_smoke_api", API / "main.py")
        if spec is None or spec.loader is None:
            raise RuntimeError("cannot load apps/api/main.py")
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        app = getattr(mod, "app", None)
        if app is None:
            errors.append("live probe: apps/api/main.py has no `app`")
        else:
            from fastapi.testclient import TestClient

            client = TestClient(app)
            resp = client.get("/health")
            if resp.status_code != 200:
                errors.append(f"live probe /health status={resp.status_code}")
            else:
                print("SMOKE LIVE: GET /health ->", resp.status_code, resp.text[:120])
            # 若存在报修路由文件，则前期 API 不得被后期覆盖掉
            repairs_py = API / "routers" / "repairs.py"
            if repairs_py.is_file() or "repairs" in (API / "main.py").read_text(
                encoding="utf-8", errors="ignore"
            ):
                r2 = client.get("/api/repairs")
                if r2.status_code >= 500:
                    errors.append(f"live probe /api/repairs status={r2.status_code}")
                elif r2.status_code == 404:
                    errors.append(
                        "live probe /api/repairs missing (later phase overwrote early routes)"
                    )
                else:
                    print("SMOKE LIVE: GET /api/repairs ->", r2.status_code)

            # ACCEPTANCE_Px HTTP 用例：区分完成 / 空壳 / 失败
            import json as _json

            cases_path = ROOT / "docs" / "acceptance_cases.json"
            if cases_path.is_file():
                try:
                    payload = _json.loads(cases_path.read_text(encoding="utf-8"))
                except Exception as exc:  # noqa: BLE001
                    errors.append(f"acceptance_cases.json unreadable: {exc}")
                    payload = {}
                hollow_needles = (
                    "新增条目",
                    "auto increment",
                    "notimplemented",
                    "not implemented",
                    "placeholder",
                    "通用占位",
                )
                report_lines = ["# 验收报告", ""]
                acc_pass, acc_hollow, acc_fail = [], [], []
                for case in payload.get("cases") or []:
                    method = str(case.get("method") or "GET").upper()
                    path = str(case.get("path") or "")
                    cid = str(case.get("id") or path)
                    if not path:
                        continue
                    try:
                        resp_c = client.request(method, path)
                    except Exception as exc:  # noqa: BLE001
                        errors.append(f"ACCEPTANCE fail: {cid} {method} {path} ({exc})")
                        acc_fail.append(cid)
                        continue
                    body = resp_c.text or ""
                    low = body.lower()
                    expect = [int(x) for x in (case.get("expect_status") or [200])]
                    verdict = "pass"
                    if case.get("optional") and resp_c.status_code == 404:
                        verdict = "pass"
                    elif resp_c.status_code >= 500 or (
                        resp_c.status_code in (404, 405, 501)
                        and resp_c.status_code not in expect
                    ):
                        verdict = "fail"
                    elif resp_c.status_code not in expect:
                        verdict = "fail"
                    elif any(n in low for n in hollow_needles):
                        verdict = "placeholder"
                    else:
                        data = None
                        try:
                            data = resp_c.json()
                        except Exception:
                            data = None
                        need_keys = case.get("required_any_keys") or []
                        if need_keys and (
                            not isinstance(data, dict)
                            or not any(k in data for k in need_keys)
                        ):
                            verdict = "placeholder"
                        item_keys = case.get("item_required_keys") or []
                        rows = []
                        if isinstance(data, dict):
                            rows = data.get("items") or data.get("products") or []
                        if item_keys and isinstance(rows, list):
                            for row in rows:
                                if isinstance(row, dict) and not all(
                                    k in row for k in item_keys
                                ):
                                    verdict = "placeholder"
                                    break
                    line = f"{verdict}: {cid} {method} {path} -> {resp_c.status_code}"
                    print("ACCEPTANCE", line)
                    report_lines.append(f"- {line}")
                    if verdict == "pass":
                        acc_pass.append(cid)
                    elif verdict == "placeholder":
                        acc_hollow.append(cid)
                        errors.append(
                            f"placeholder endpoint: {cid} {method} {path}"
                        )
                    else:
                        acc_fail.append(cid)
                        errors.append(
                            f"ACCEPTANCE fail: {cid} {method} {path} status={resp_c.status_code}"
                        )
                report_path = ROOT / "docs" / "ACCEPTANCE_REPORT.md"
                report_path.parent.mkdir(parents=True, exist_ok=True)
                report_path.write_text(
                    "\\n".join(
                        [
                            "# 验收报告",
                            "",
                            f"- 完成：{', '.join(acc_pass) or '无'}",
                            f"- 空壳：{', '.join(acc_hollow) or '无'}",
                            f"- 失败：{', '.join(acc_fail) or '无'}",
                            "",
                            *report_lines[2:],
                            "",
                        ]
                    ),
                    encoding="utf-8",
                )
    except Exception as exc:  # noqa: BLE001
        # 依赖未装时降级为警告，不直接失败（语法检查仍生效）
        msg = f"live probe skipped/failed: {exc}"
        if "No module named" in str(exc) or "cannot import" in str(exc).lower():
            warnings.append(msg)
        else:
            errors.append(msg)

# 数据层：若存在 db.py，跑跨租户隔离探活
db_py = API / "db.py"
if db_py.is_file() and not errors:
    try:
        import importlib.util as _ilu

        _spec = _ilu.spec_from_file_location("mawp_smoke_db", db_py)
        if _spec is None or _spec.loader is None:
            raise RuntimeError("cannot load apps/api/db.py")
        _mod = _ilu.module_from_spec(_spec)
        _spec.loader.exec_module(_mod)
        _fn = getattr(_mod, "tenant_isolation_ok", None)
        if callable(_fn):
            _ok, _detail = _fn()
            if not _ok:
                errors.append(f"tenant isolation failed: {_detail}")
            else:
                print("SMOKE TENANT:", _detail)
        else:
            warnings.append("apps/api/db.py missing tenant_isolation_ok()")
    except Exception as exc:  # noqa: BLE001
        errors.append(f"tenant isolation probe error: {exc}")

    mig_dir = ROOT / "docs" / "migrations"
    if not mig_dir.is_dir() or not list(mig_dir.glob("*.sql")):
        warnings.append("docs/migrations missing *.sql (data-layer scaffold incomplete)")
    if not list((ROOT / "scripts").glob("seed_*.py")):
        warnings.append("scripts/seed_*.py missing (data-layer scaffold incomplete)")
    if not (API / "cache.py").is_file():
        warnings.append("apps/api/cache.py missing (optional cache scaffold)")

# 扫描 models*.py 缺 tenant_id / community_id
import ast as _ast

for _mp in sorted(API.glob("models*.py")) + sorted(API.glob("*_models.py")):
    if _mp.name.startswith("_"):
        continue
    try:
        _tree = _ast.parse(_mp.read_text(encoding="utf-8", errors="ignore"))
    except SyntaxError:
        continue
    for _node in _tree.body:
        if not isinstance(_node, _ast.ClassDef):
            continue
        if _node.name.endswith(("Create", "Update")) or _node.name in {
            "BaseModel",
            "Base",
            "ItemCreate",
            "OrderCreate",
            "RepairCreate",
        }:
            continue
        _fields = set()
        for _st in _node.body:
            if isinstance(_st, _ast.AnnAssign) and isinstance(_st.target, _ast.Name):
                _fields.add(_st.target.id)
        if "id" not in _fields:
            continue
        _bases = []
        for _b in _node.bases:
            if isinstance(_b, _ast.Name):
                _bases.append(_b.id)
            elif isinstance(_b, _ast.Attribute):
                _bases.append(_b.attr)
        if not any(x in {"BaseModel", "Base"} for x in _bases) and "id" not in _fields:
            continue
        if "tenant_id" not in _fields or "community_id" not in _fields:
            errors.append(
                f"missing tenant fields: {_mp.name}::{_node.name} "
                "(need tenant_id + community_id)"
            )

if warnings:
    print("SMOKE WARN:")
    for w in warnings:
        print("-", w)

if errors:
    print("SMOKE FAIL:")
    for e in errors:
        print("-", e)
    raise SystemExit(1)

print("SMOKE PASS: L0 syntax/assembly ok (set MAWP_SMOKE_LIVE=1 for HTTP)")
sys.exit(0)
'''


def normalize_tasks(raw: Any, *, goal: str = "") -> list[dict[str, Any]]:
    """把 planner/requirement 任务列表规范化为 [{id,title,description}, ...]。"""
    out: list[dict[str, Any]] = []
    if isinstance(raw, list):
        for i, item in enumerate(raw):
            if isinstance(item, dict):
                tid = str(item.get("id") or f"T{i + 1}")
                title = str(
                    item.get("title")
                    or item.get("name")
                    or item.get("summary")
                    or tid
                )
                desc = str(
                    item.get("description")
                    or item.get("goal")
                    or item.get("detail")
                    or title
                )
                out.append({"id": tid, "title": title[:120], "description": desc[:800]})
            elif isinstance(item, str) and item.strip():
                out.append(
                    {
                        "id": f"T{i + 1}",
                        "title": item.strip()[:120],
                        "description": item.strip()[:800],
                    }
                )
    if not out:
        g = (goal or "implement phase increment").strip() or "implement phase increment"
        out = [
            {
                "id": "T1",
                "title": g[:80],
                "description": f"在 project_root 下实现：{g[:400]}",
            }
        ]
    return out


def extract_tasks_from_ctx(
    input_data: dict[str, Any],
    nodes_outputs: dict[str, dict[str, Any]],
    *,
    goal: str = "",
    params: dict[str, Any] | None = None,
) -> list[dict[str, Any]]:
    from mawp.runtime.task_split import prefer_split_tasks

    planner_raw = (
        (nodes_outputs.get("planner") or {}).get("tasks")
        or (nodes_outputs.get("requirement") or {}).get("tasks")
        or []
    )
    injected_raw = (
        (params or {}).get("tasks")
        or input_data.get("tasks")
        or []
    )
    chosen = prefer_split_tasks(
        normalize_tasks(planner_raw, goal=goal) if planner_raw else [],
        normalize_tasks(injected_raw, goal=goal) if injected_raw else [],
    )
    return chosen or normalize_tasks([], goal=goal)


def smoke_script_rel(project_root: str) -> str:
    root = project_root.replace("\\", "/").rstrip("/")
    return f"{root}/scripts/smoke_check.py"


def default_metric_command(project_root: str) -> str:
    rel = smoke_script_rel(project_root)
    return f'python "{rel}"'


def write_smoke_script(workspace: Path, project_root: str) -> Path:
    """写入 {project_root}/scripts/smoke_check.py，返回绝对路径。"""
    root = project_root.replace("\\", "/").rstrip("/")
    path = workspace / root / "scripts" / "smoke_check.py"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(SMOKE_SCRIPT, encoding="utf-8")
    return path


def write_phase_acceptance_note(
    workspace: Path,
    project_root: str,
    *,
    phase_id: str | None,
    metric_command: str,
    title: str = "",
    goal: str = "",
) -> Path:
    from mawp.runtime.acceptance_gate import write_acceptance_cases

    root = project_root.replace("\\", "/").rstrip("/")
    pid = (phase_id or "phase").upper()
    cases_path = write_acceptance_cases(
        workspace,
        project_root,
        phase_id=phase_id,
        title=title,
        goal=goal,
    )
    cases_doc = cases_path.read_text(encoding="utf-8")
    path = workspace / root / "docs" / f"ACCEPTANCE_{pid}.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        f"""# 验收说明 · {pid}

## 冒烟命令（Deliver Testing Agent）

```bash
{metric_command}
```

## HTTP 验收用例

对照 `docs/acceptance_cases.json` 自动发请求。  
**路由存在 ≠ 业务完成**：返回「新增条目」/ 通用 `/items` 壳记为空壳，404 记为失败；只有用例通过才允许分期标完成。

```json
{cases_doc}
```

## 检查项

1. `apps/api` 存在且全部 `.py` 可 `py_compile`
2. `apps/web` 存在且有 `index.html` 或前端源文件
3. Coding 任务循环产出的 `changed_files` 落在 `project_root` 下
4. **L0 默认**（快）：`py_compile` + `include_router` 装配 + 入口页。不装依赖、不起 TestClient。
5. **L1**（`MAWP_SMOKE_LIVE=1`）：`TestClient` 打 `GET /health` 与 `acceptance_cases.json`
6. **L2**（`MAWP_SMOKE_API_INSTALL=1` / `MAWP_SMOKE_WEB_BUILD=1`）：pip / npm
7. **装配门禁**：`routers/*.py` 与根目录 `module_*.py` 若定义了 `APIRouter`，必须在 `main.py` 里 `include_router`；`apps/web/*.html` 业务页必须出现在 `index.html`
8. **数据层**：存在 `apps/api/db.py` 时跑跨租户隔离；`models*.py` 实体须含 `tenant_id` + `community_id`

## 人工联调（可选）

```bash
cd {root}/apps/api && pip install -r requirements.txt && uvicorn main:app --reload --port 8001
cd {root}/apps/web && npx --yes serve -l 5175 .
```
""",
        encoding="utf-8",
    )
    return path


def ensure_project_metric(
    workspace: Path,
    params: dict[str, Any],
    *,
    write_acceptance: bool = True,
) -> str | None:
    """project_mode 时确保有 metric_command；必要时写入冒烟脚本。

    会就地修改 ``params``。返回最终 metric_command（若无 project_root 则 None）。
    """
    if not params.get("project_mode"):
        existing = params.get("metric_command") or params.get("verify_command")
        return str(existing).strip() if existing else None

    project_root = str(params.get("project_root") or "").replace("\\", "/").rstrip("/")
    if not project_root:
        return None

    metric = str(
        params.get("metric_command") or params.get("verify_command") or ""
    ).strip()
    write_smoke_script(workspace, project_root)
    if not metric:
        metric = default_metric_command(project_root)
        params["metric_command"] = metric

    if write_acceptance and not params.get("_acceptance_written"):
        write_phase_acceptance_note(
            workspace,
            project_root,
            phase_id=str(params.get("phase_id") or "") or None,
            metric_command=metric,
            title=str(params.get("project_title") or params.get("title") or ""),
            goal=str(params.get("goal") or ""),
        )
        params["_acceptance_written"] = True

    return metric
